### ISSUE TITLE
没办法生成EnvironmentSwitcher

### ISSUE THREAD

**Issue by timuyishijian** [CodeXiaoMai/EnvironmentSwitcher#20]
为啥我的项目没办法生成EnvironmentSwitcher文件。我新建一个新项目，按例子集成是ok的。但是集成到我的项目就是没办法生成

**Comment by timuyishijian** [comment]
报错
Task :app:kaptDebugKotlin
javax.annotation.processing.FilerException: Attempt to recreate a file for type com.xiaomai.environmentswitcher.EnvironmentSwitcher
	at com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:522)
	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:396)
	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:114)
	at com.xiaomai.environmentswitcher.compiler.EnvironmentSwitcherCompilerDebug.process(EnvironmentSwitcherCompilerDebug.java:254)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)
	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)
	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:158)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:50)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:59)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:53)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:745)

**Comment by CodeXiaoMai** [comment]
可以提供一个脱敏的demo吗

**Comment by timuyishijian** [comment]
选择 debugSigning时不会生成




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodeXiaoMai/EnvironmentSwitcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月9日(星期二) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CodeXiaoMai/EnvironmentSwitcher] 没办法生成EnvironmentSwitcher (#20)





 
可以提供一个脱敏的demo吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

MyApplication4.rar (381.8K, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=73333365883bce996639aa7a4433064900070b0657040c0319510704011e005306571e075006064b050505035402005602020a566221342b4d7243150e5a5707405a5c0b561d460746330e&t=exs_ftn_download&code=433eb34f

**Comment by CodeXiaoMai** [comment]
看了一下你提供的demo，gradle 配置有问题，你需要针对你的 buildType 定制配置一下：

加上下面这行就好了，其他的 flavor 同理。
``` groovy
debugSigningAnnotationProcessor "com.xiaomai.environmentswitcher:environmentswitcher-compiler:1.5.2"
```

**Comment by timuyishijian** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月10日(星期三) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CodeXiaoMai/EnvironmentSwitcher] 没办法生成EnvironmentSwitcher (#20)





 
看了一下你提供的demo，gradle 配置有问题，你需要针对你的 buildType 定制配置一下：
 
加上下面这行就好了，其他的 flavor 同理。
 debugSigningAnnotationProcessor "com.xiaomai.environmentswitcher:environmentswitcher-compiler:1.5.2"
